# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-02 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=256)),
                ('institution', models.CharField(max_length=256)),
                ('brief_description', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('post_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('filled', models.BooleanField()),
            ],
            options={
                'ordering': ['expiration_date', 'post_date', 'institution', 'job_title'],
            },
        ),
    ]
