# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-04 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-expiration_date', '-post_date', 'institution', 'job_title']},
        ),
    ]
