# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-28 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterMine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
            ],
        ),
    ]
