# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-28 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intermine_mgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intermine',
            options={'ordering': ['name'], 'verbose_name_plural': 'InterMines'},
        ),
    ]
