# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-17 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('announcements', '0004_remove_announcement_my_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='announcements_cms_integration_announcementpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.Announcement')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
