# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-17 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements_cms_integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementpluginmodel',
            name='announcement',
        ),
    ]
