# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-05 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('species_mgr', '0005_auto_20181004_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_mgr.Organization', verbose_name='organization that provides it')),
                ('species', models.ManyToManyField(to='species_mgr.Species', verbose_name='its related species')),
            ],
        ),
    ]
