# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-05 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_mgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['text']},
        ),
        migrations.AddField(
            model_name='resource',
            name='text',
            field=models.CharField(default='', max_length=256),
        ),
    ]
