# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-05 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_mgr', '0002_auto_20181005_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='text',
            field=models.CharField(default='', max_length=256, verbose_name='Text (if different from Organization)'),
        ),
    ]
