# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-12 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_mgr', '0004_auto_20181005_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['org', 'text']},
        ),
    ]
