# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-18 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_mgr', '0005_auto_20181012_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_data',
            field=models.BooleanField(default=False, verbose_name='Data Download'),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_tour',
            field=models.BooleanField(default=False, verbose_name='Tour'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='species',
            field=models.ManyToManyField(blank=True, to='species_mgr.Species', verbose_name='its related species'),
        ),
    ]
