# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-23 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_mgr', '0006_auto_20181018_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='tour_hints',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
