# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-01 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_mgr', '0007_resource_tour_hints'),
    ]

    operations = [
        migrations.RenameField('Resource', 'tour_hints', 'hints'),
    ]
