# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-02 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_mgr', '0009_organization_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
