# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-05 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_mgr', '0010_auto_20181102_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDownload',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resource_mgr.Resource')),
            ],
            bases=('resource_mgr.resource',),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='is_data',
        ),
    ]
