# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-07 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_mgr', '0013_auto_20181127_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolanalysistype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tooldatatype',
            options={'ordering': ['name']},
        ),
    ]
