# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-03 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_mgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['genus_name', 'species_name', 'common_name'], 'verbose_name_plural': 'Species'},
        ),
        migrations.AddField(
            model_name='species',
            name='icon_filename',
            field=models.CharField(default='', max_length=256),
        ),
    ]
