# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-04 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_mgr', '0002_auto_20181003_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='icon',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
