# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-04 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('species_mgr', '0004_remove_species_icon_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='icon',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_icons', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
