# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-02 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkoutService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_prefix', models.CharField(max_length=255, verbose_name='URL Prefix')),
                ('gene_example', models.CharField(max_length=255)),
                ('url_suffix', models.CharField(max_length=255, verbose_name="URL Suffix (probably 'json')")),
            ],
            options={
                'ordering': ['url_prefix', 'url_suffix'],
            },
        ),
    ]
