# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-02 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkout_mgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkoutservice',
            name='url_suffix',
            field=models.CharField(max_length=255, verbose_name='URL Suffix'),
        ),
    ]
