# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-12 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkout_mgr', '0003_auto_20190712_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genelinkout',
            old_name='gene_example0',
            new_name='gene_example',
        ),
    ]
