# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkout_mgr', '0004_auto_20190712_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkoutservice',
            name='regex',
            field=models.CharField(default='(.+)', help_text='Pattern of captures must match URL format', max_length=255, verbose_name='Regular Expression'),
        ),
        migrations.AddField(
            model_name='linkoutservice',
            name='true_linkouts',
            field=models.BooleanField(default=True, help_text='Uncheck to create pseudo-linkouts on the fly', verbose_name='URL returns true linkouts'),
        ),
        migrations.AlterField(
            model_name='linkoutservice',
            name='url_format',
            field=models.CharField(help_text='Represent fields as $1, $2, etc', max_length=255, verbose_name='URL Format'),
        ),
    ]
