# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-16 19:50
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('announcements', '0002_announcement_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='my_placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='cms-plugin-45', to='cms.Placeholder'),
        ),
    ]
