# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-16 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_my_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='my_placeholder',
        ),
    ]
